=== MaxBobisch/WBA2/Phase1/bin/aufgabe3.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

<!-- definition of simple elements -->
<xs:element name="tag">
  <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:pattern value="[0-3][0-9]"/>
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="31"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="monat">
  <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:pattern value="[0-1][0-9]"/>
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="12"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="jahr">
  <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:pattern value="[0-9][0-9][0-9][0-9]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="name" type="xs:string"/>
<xs:element name="url" type="xs:string"/>
<xs:element name="anzahl_personen" type="xs:integer"/>
<xs:element name="menge" type="xs:decimal"/>
<xs:element name="einheit" type="xs:string"/>
<xs:element name="nummer" type="xs:integer"/>
<xs:element name="inhalt" type="xs:string"/>
<xs:element name="schwierigkeitsgrad" type="xs:string"/>


<!-- definition of complex elements -->
<xs:element name="datum">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="tag"/>
      <xs:element ref="monat"/>
      <xs:element ref="jahr"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="autor">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="datum"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!-- 
<xs:element name="bild">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="autor"/>
      <xs:element ref="nummer"/>
      <xs:element ref="url"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
 -->
 
 <!-- 
<xs:element name="bilder">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="bild" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
 -->

<xs:element name="zutat">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="menge" minOccurs="0"/>
      <xs:element ref="einheit" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="zutaten">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="anzahl_personen"/>
      <xs:element ref="zutat" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="schritt">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="nummer"/>
      <xs:element ref="inhalt"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="zubereitung">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="arbeitszeit"/>
      <xs:element ref="schwierigkeitsgrad"/>
      <xs:element ref="brennwert"/>
      <xs:element ref="anleitung"/>
      <xs:element ref="weitere_rezepte" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="brennwert">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="menge"/>
      <xs:element ref="einheit"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="anleitung">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="schritt" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="arbeitszeit">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="menge"/>
      <xs:element ref="einheit"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<!-- 
<xs:element name="quelle">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="datum"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
-->

<!--  
<xs:element name="kommentar">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="beschreibung"/>
      <xs:element ref="quelle"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
-->

<!--  
<xs:element name="kommentare">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="kommentar" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
-->


<!-- KANN EIN REZEPT AUF EIN ANDERES VERWEISEN? -->
<xs:element name="weitere_rezepte">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="url" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!-- root-Element 'rezept' -->
<xs:element name="rezept">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="zutaten"/>
      <xs:element ref="zubereitung"/>
      <!-- <xs:element ref="bilder"/> -->
      <!-- <xs:element ref="kommentare"/> -->
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== MaxBobisch/WBA2/Phase1/bin/aufgabe3.xml
<?xml version="1.0" encoding="UTF-8"?>

<rezept
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="aufgabe3.xsd">
	<name>Lenchen’s Schokoladenkuchen</name>
	<zutaten>
		<anzahl_personen>16</anzahl_personen>
		<zutat>
			<name>Butter</name>
			<menge>200</menge>
			<einheit>g</einheit>
		</zutat>
		<zutat>
			<name>Zucker</name>
			<menge>200</menge>
			<einheit>g</einheit>
		</zutat>
		<zutat>
			<name>Schokolade, Blockschokolade</name>
			<menge>200</menge>
			<einheit>g</einheit>
		</zutat>
		<zutat>
			<name>Mehl</name>
			<menge>120</menge>
			<einheit>g</einheit>
		</zutat>
		<zutat>
			<name>Backpulver</name>
			<menge>0.5</menge>
			<einheit>Teeloeffel</einheit>
		</zutat>
		<zutat>
			<name>Vanillezucker</name>
			<menge>1</menge>
			<einheit>Paket</einheit>
		</zutat>
		<zutat>
			<name>Ei</name>
			<menge>4</menge>
			<einheit>Stueck</einheit>
		</zutat>
	</zutaten>
	<zubereitung>
	  <arbeitszeit>
		<menge>1</menge>
		<einheit>Stunde</einheit>
	  </arbeitszeit>
	  <schwierigkeitsgrad>normal</schwierigkeitsgrad>
	  <brennwert>
		<menge>295</menge>
		<einheit>kcal</einheit>
	  </brennwert>
	<anleitung>
	<schritt>
		<nummer>1</nummer>
		<inhalt>Butter und Schokolade im Wasserbad schmelzen.</inhalt>
	</schritt>
	<schritt>
		<nummer>2</nummer>
		<inhalt>Eier trennen.</inhalt>
	</schritt>
	<schritt>
		<nummer>3</nummer>
		<inhalt>Eiweiß steif schlagen.</inhalt>
	</schritt>
	<schritt>
		<nummer>4</nummer>
		<inhalt>Eigelbe, Zucker und Vanillezucker verrühren.</inhalt>
	</schritt>
	<schritt>
		<nummer>5</nummer>
		<inhalt>Geschmolzene Butter-Schokomasse hinzufügen und mischen.</inhalt>
	</schritt>
	<schritt>
		<nummer>6</nummer>
		<inhalt>Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen Eiweiße vorsichtig unterheben.</inhalt>
	</schritt>
	<schritt>
		<nummer>7</nummer>
		<inhalt>In eine gut gefettete Form geben.</inhalt>
	</schritt>
	<schritt>
		<nummer>8</nummer>
		<inhalt>Bei 180°Grad 40 – 50 Minuten backen. 
			<!-- <backvorgang>
				<temperatur>
					<menge>180</menge>
					<einheit>°C</einheit>
				</temperatur>
				<dauer>
					<mindestens>
						<menge>40</menge>
					</mindestens>
					<hoechstens>
						<menge>50</menge>
					</hoechstens>
				<einheit>minuten</einheit>
				</dauer>
			</backvorgang> -->
		</inhalt>
	</schritt> 
	</anleitung>
	</zubereitung>
</rezept>
