=== MaxBobisch/WBA2/WBA2Phase1/src/aufgabe3.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

<!-- definition of simple elements -->
<!--  <xs:element name="tag">
  <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:pattern value="[0-3][0-9]"/>
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="31"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="monat">
  <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:pattern value="[0-1][0-9]"/>
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="12"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="jahr">
  <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:pattern value="[0-9][0-9][0-9][0-9]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>   -->

<xs:element name="name" type="xs:string"/>
<xs:element name="url" type="xs:string"/>
<xs:element name="avatar" type="xs:string"/>
<xs:element name="anzahl_personen" type="xs:integer"/>
<xs:element name="inhalt" type="xs:string"/>
<xs:element name="schwierigkeitsgrad" type="xs:string"/>
<xs:element name="datum" type="xs:dateTime"/>
<xs:element name="bildbesitzer" type="xs:string"/>

<!-- Attribute -->
<xs:attribute name="menge" type="xs:decimal"/>
<xs:attribute name="einheit" type="xs:string"/>
<xs:attribute name="nummer" type="xs:integer"/>
<xs:attribute name="rezeptid" type="xs:integer"/>


<!-- definition of complex elements -->
<!--  <xs:element name="datum">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="tag"/>
      <xs:element ref="monat"/>
      <xs:element ref="jahr"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>-->

<xs:element name="autor">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="datum"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="bild">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="bildbesitzer"/>
      <xs:element ref="url"/>
    </xs:sequence>
    <xs:attribute ref="nummer"/>
  </xs:complexType>
</xs:element>
 
<xs:element name="bilder">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="bild" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="zutat">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
    </xs:sequence>
    <xs:attribute ref="menge"/>
    <xs:attribute ref="einheit"/>
  </xs:complexType>
</xs:element>

<xs:element name="zutaten">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="anzahl_personen"/>
      <xs:element ref="zutat" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="schritt">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="inhalt"/>
    </xs:sequence>
    <xs:attribute ref="nummer"/>
  </xs:complexType>
</xs:element>

<xs:element name="zubereitung">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="arbeitszeit"/>
      <xs:element ref="schwierigkeitsgrad"/>
      <xs:element ref="brennwert"/>
      <xs:element ref="anleitung"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="brennwert">
  <xs:complexType>
    <xs:sequence>
    </xs:sequence>
    <xs:attribute ref="menge"/>
    <xs:attribute ref="einheit"/>
  </xs:complexType>
</xs:element>

<xs:element name="anleitung">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="schritt" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="arbeitszeit">
  <xs:complexType>
    <xs:sequence>
    </xs:sequence>
    <xs:attribute ref="menge"/>
    <xs:attribute ref="einheit"/>
  </xs:complexType>
</xs:element>


<xs:element name="quelle">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="avatar"/>
      <xs:element ref="datum"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="kommentar">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="inhalt"/>
      <xs:element ref="quelle"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
 
<xs:element name="kommentare">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="kommentar" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!-- KANN EIN REZEPT AUF EIN ANDERES VERWEISEN? -->

<xs:element name="rezept">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="zutaten"/>
      <xs:element ref="zubereitung"/>
      <xs:element ref="bilder"/>
      <xs:element ref="kommentare"/>
    </xs:sequence>
    <xs:attribute ref="rezeptid" use="required"/>
  </xs:complexType>
</xs:element>

<!-- root-Element 'rezeptsammlung' -->
<xs:element name="rezeptsammlung">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="rezept" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== MaxBobisch/WBA2/WBA2Phase1/bin/aufgabe3-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<rezeptsammlung xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../bin/aufgabe3.xsd">
  <rezept rezeptid="202">
    <name>Russischer Zupfkuchen</name>
    <zutaten>
      <anzahl_personen>6</anzahl_personen>
      <zutat einheit="g" menge="300">
        <name>Mehl</name>
      </zutat>
      <zutat einheit="kg" menge="0.375">
        <name>Butter</name>
      </zutat>
      <zutat einheit="g" menge="600">
        <name>Zucker</name>
      </zutat>
      <zutat einheit="Päckchen" menge="0.5">
        <name>Backpulver</name>
      </zutat>
      <zutat einheit="Esslöffel" menge="5">
        <name>Kakao</name>
      </zutat>
      <zutat einheit="Spritzer" menge="1">
        <name>Zitronensaft</name>
      </zutat>
      <zutat einheit="Päckchen" menge="1">
        <name>Vanillepudding</name>
      </zutat>
      <zutat einheit="Stück" menge="3">
        <name>Ei</name>
      </zutat>
    </zutaten>
    <zubereitung>
      <arbeitszeit einheit="Stunde" menge="1"/>
      <schwierigkeitsgrad>leicht</schwierigkeitsgrad>
      <brennwert einheit="kcal" menge="3000"/>
      <anleitung>
        <schritt nummer="1">
          <inhalt>Füllung: Quark, Vanillepuddingpulver, 125g Butter, 300g Zucker, Eier und den Spritzer Zitrone in einer Schüssel glatt rühren.</inhalt>
        </schritt>
        <schritt nummer="2">
          <inhalt>Streusel: 300g Zucker, Mehl, Kakao und 250g Butter zu einem Teig kneten.</inhalt>
        </schritt>
        <schritt nummer="3">
          <inhalt>Die Hälfte der Streusel auf dem Blech verteilen, die Füllung darauf verteilen und mit den restlichen Streuseln verzieren.</inhalt>
        </schritt>
        <schritt nummer="4">
          <inhalt>Bei 180° C 45 Minuten Backen.</inhalt>
        </schritt>
        <schritt nummer="5">
          <inhalt>Komplett abkühlen lassen.</inhalt>
        </schritt>
      </anleitung>
    </zubereitung>
    <bilder>
	  <bild nummer="34">
	    <bildbesitzer>ralf12345</bildbesitzer>
	      <url>http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/42942-960x7ralf12345.jpg</url>
	  </bild>
	</bilder>
	<kommentare>
	  <kommentar>
	    <inhalt>Lecker, aber etwas mächtig. Nix für Zwischendurch.</inhalt>
	    <quelle>
	      <name>ralf12345</name>
	      <avatar>http://static.chefkoch-cdn.de/ck.de/avatar/mypic2.jpg</avatar>
	      <datum>2013-03-17T08:29:00</datum>
	    </quelle>
	  </kommentar>
	</kommentare> 
  </rezept>
</rezeptsammlung>

=== MaxBobisch/WBA2/Phase1/src/aufgabe3-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<rezeptsammlung xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../bin/aufgabe3.xsd">
  <rezept rezeptid="203">
    <name>Mizza</name>
    <zutaten>
      <anzahl_personen>4</anzahl_personen>
      <zutat einheit="kg" menge="1">
        <name>Mehl</name>
      </zutat>
      <zutat>
        <name>Salz</name>
      </zutat>
      <zutat einheit="ml" menge="625">
        <name>Wasser</name>
      </zutat>
      <zutat einheit="Schuss" menge="1">
        <name>Olivenoel</name>
      </zutat>
      <zutat einheit="Packung" menge="0.3">
        <name>Hefe</name>
      </zutat>
    </zutaten>
    <zubereitung>
      <arbeitszeit einheit="Stunde" menge="2"/>
      <schwierigkeitsgrad>fortgeschritten</schwierigkeitsgrad>
      <brennwert einheit="kcal" menge="1000"/>
      <anleitung>
        <schritt nummer="1">
          <inhalt>alles (außer 400g des Mehls) mischen in einer Schuessel.</inhalt>
        </schritt>
        <schritt nummer="2">
          <inhalt>20 min. gehen lassen</inhalt>
        </schritt>
        <schritt nummer="3">
          <inhalt>Rest des Mehls hinzugeben, alles kneten und nochmals 20 min. gehen lassen.</inhalt>
        </schritt>
        <schritt nummer="4">
          <inhalt>mit Belag deiner Wahl belegen. mit viel Liebe :)</inhalt>
        </schritt>
        <schritt nummer="5">
          <inhalt>Im auf 250°C erhitzten Backofen (je heißer desto besser!) ca. 10 min. backen.</inhalt>
        </schritt>
      </anleitung>
    </zubereitung>
    <bilder>
	  <bild nummer="1">
	    <bildbesitzer>Mario</bildbesitzer>
	    <url>http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/42942-960x7mario.jpg</url>
	  </bild>
	</bilder>
	<kommentare>
	  <kommentar>
	    <inhalt>Die beste Pizza von der ganzen Welt, das hat auch meine Mama gesagt! Bist du Italieren?</inhalt>
	    <quelle>
	      <name>Lieschen</name>
	      <avatar>http://static.chefkoch-cdn.de/ck.de/avatar/alligator.jpg</avatar>
	      <datum>2013-04-07T18:49:00</datum>
	    </quelle>
	  </kommentar>
	</kommentare> 
  </rezept>
</rezeptsammlung>

=== MaxBobisch/WBA2/Phase1/src/aufgabe3.xml
<?xml version="1.0" encoding="UTF-8"?>


<rezeptsammlung
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="aufgabe3.xsd">
<rezept>
	<name>Lenchen’s Schokoladenkuchen</name>
	<zutaten>
		<anzahl_personen>16</anzahl_personen>
		<zutat menge="200" einheit="g">
			<name>Butter</name>
		</zutat>
		<zutat menge="200" einheit="g">
			<name>Zucker</name>
		</zutat>
		<zutat menge="200" einheit="g">
			<name>Schokolade, Blockschokolade</name>
		</zutat>
		<zutat menge="120" einheit="g">
			<name>Mehl</name>
		</zutat>
		<zutat menge="0.5" einheit="Teeloeffel">
			<name>Backpulver</name>
		</zutat>
		<zutat menge="1" einheit="Paket">
			<name>Vanillezucker</name>
		</zutat>
		<zutat menge="4" einheit="Stueck">
			<name>Ei</name>
		</zutat>
	</zutaten>
	<zubereitung>
	  <arbeitszeit menge="1" einheit="Stunde"/>
	  <schwierigkeitsgrad>normal</schwierigkeitsgrad>
	  <brennwert menge="295" einheit="kcal"/>
	<anleitung>
	<schritt nummer="1">
		<inhalt>Butter und Schokolade im Wasserbad schmelzen.</inhalt>
	</schritt>
	<schritt nummer="2">
		<inhalt>Eier trennen.</inhalt>
	</schritt>
	<schritt nummer="3">
		<inhalt>Eiweiß steif schlagen.</inhalt>
	</schritt>
	<schritt nummer="4">
		<inhalt>Eigelbe, Zucker und Vanillezucker verrühren.</inhalt>
	</schritt>
	<schritt nummer="5">
		<inhalt>Geschmolzene Butter-Schokomasse hinzufügen und mischen.</inhalt>
	</schritt>
	<schritt nummer="6">
		<inhalt>Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen Eiweiße vorsichtig unterheben.</inhalt>
	</schritt>
	<schritt nummer="7">
		<inhalt>In eine gut gefettete Form geben.</inhalt>
	</schritt>
	<schritt nummer="8">
		<inhalt>Bei 180°Grad 40 – 50 Minuten backen. 
			<!-- <backvorgang>
				<temperatur>
					<menge>180</menge>
					<einheit>°C</einheit>
				</temperatur>
				<dauer>
					<mindestens>
						<menge>40</menge>
					</mindestens>
					<hoechstens>
						<menge>50</menge>
					</hoechstens>
				<einheit>minuten</einheit>
				</dauer>
			</backvorgang> -->
		</inhalt>
	</schritt> 
	</anleitung>
	</zubereitung>
	<!-- REPRÄSENTATIV 1 BILD & 1 KOMMENTAR -->
	<bilder>
	  <bild>
	    <bildbesitzer>Mutschkabras</<bildbesitzer>
	    <nummer>20</nummer>
	    <url>http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/42942-960x720-lenchen-s-schokoladenkuchen.jpg</url>
	  </bild>
	</bilder>
	<kommentare>
	  <kommentar>
	    <inhalt>Habe Deinen Kuchen gestern gebacken (kleine Abwandlung: statt Blockschokolade hatte ich nur Kuvertüre, zartbitter und ich habe noch etwas Rumaroma und eine Prise Salz dazugegeben) mein LAG war total begeistert. Ich übrigends auch, super Rezept.</inhalt>
	    <quelle>
	      <name>swieselchen</name>
	      <avatar>http://static.chefkoch-cdn.de/ck.de/avatar/5ab77fec95e69919037a2ea283c4d6a6-60fix.jpg</avatar>
	      <datum>2002-02-07T18:49:00</datum>
	    </quelle>
	  </kommentar>
	</kommentare> 
</rezept>
</rezeptsammlung>
